<?php declare(strict_types=1);
namespace PZBot\Events\Handlers\ChatGptMessages;

use PZBot\Events\HandlerInterface;
use PZBot\Exceptions\Checked\PathWasNotFoundException;
use PZBot\Helpers\TelegramRequestHelper;
use PZBot\Service\ImageResolver;
use PZBot\Service\OpenAI\ChatGpt;


class ChatGptSylphietteMessageHandler extends ChatGptMessage
{
  function getMessageFormat(): string
  {
    return "сгенерируй милую фразу, в которой ты в роли стеснительной девочки эльфийки коротко желаешь %s. Без слов о том, что ты искуственный интеллект. Не говоря о том, что ты стеснительная девочка эльфийка. Фараз должна быть адресована одному человеку. В предложении должна чувствоваться скромность и стеснение, а самое главное отсутствовать навязчивость"; // TODO: Change the autogenerated stub
  }

  function getImageFolder(): string
  {
    return '/sylphiette'; // TODO: Change the autogenerated stub
  }
}