<?php declare(strict_types=1);
namespace PZBot\Events\Handlers\ChatGptMessages;

use PZBot\Events\HandlerInterface;
use PZBot\Exceptions\Checked\PathWasNotFoundException;
use PZBot\Helpers\TelegramRequestHelper;
use PZBot\Service\ImageResolver;
use PZBot\Service\OpenAI\ChatGpt;


class ChatGptTsundereMessageHandler extends ChatGptMessage
{
  function getMessageFormat(): string
  {
    return "сгенерируй фразу, в которой ты в роли цундере девочки коротко говоришь \"%s\" в еë стиле. Без слов о том, что ты искуственный интеллект"; // TODO: Change the autogenerated stub
  }

  function getImageFolder(): string
  {
    return '/tohsaka'; // TODO: Change the autogenerated stub
  }
}