name: Docker Image CI

on:
  schedule:
  - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the latest version
        uses: actions/checkout@v3

      - shell: bash
        env:
          USER: ${{ secrets.DOCKERHUB_USERNAME }}
          PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "username: $USER"
          echo "pass: $PASS"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Check the latest version and push new versions
        run: scripts/get_updates.sh